
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Sep 25 01:50:27 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_ROUND = 29;
  public static final int CONST = 3;
  public static final int CHAR = 24;
  public static final int NAMESPACE = 20;
  public static final int USING = 21;
  public static final int SEMI = 8;
  public static final int CONTINUE = 16;
  public static final int LEFT_CURLY = 32;
  public static final int LESS = 46;
  public static final int MINUS = 37;
  public static final int FOR = 18;
  public static final int STATIC = 19;
  public static final int AND = 42;
  public static final int OR = 43;
  public static final int BOOL = 25;
  public static final int COMMA = 10;
  public static final int CLASS = 5;
  public static final int INC = 34;
  public static final int DIV = 39;
  public static final int RIGHT_CURLY = 33;
  public static final int PLUS = 36;
  public static final int ASSIGN = 12;
  public static final int IF = 13;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int MUL = 38;
  public static final int MOD = 40;
  public static final int NUMBER = 26;
  public static final int BREAK = 15;
  public static final int IDENT = 27;
  public static final int VOID = 4;
  public static final int EQ = 44;
  public static final int LEFT_SQUARE = 30;
  public static final int COLON = 9;
  public static final int ELSE = 14;
  public static final int POINT = 11;
  public static final int READ = 23;
  public static final int NOT_EQ = 45;
  public static final int LESS_EQ = 49;
  public static final int EXTENDS = 6;
  public static final int PROG = 2;
  public static final int RIGHT_SQUARE = 31;
  public static final int GR_EQ = 48;
  public static final int LEFT_ROUND = 28;
  public static final int DEC = 35;
  public static final int MAX = 41;
  public static final int GR = 47;
  public static final int PRINT = 22;
}

